baseURL = "http://yottabytt.com/"
title = "yottabytt"
languageCode = "en-us"
buildDrafts = true
theme = "cocoa-eh"

[params]
logofile = "images/YBWhite.png"
faviconfile = "images/YB.png"
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 IST"
latestpostcount = 5
github = "yottabytt"
stackexchange = "yottabytt"
email = "yottabytt@gmail.com"
